name: "💻 Generar Ejecutable Raylib C++ WoW Match-3"

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-pc:
    name: 🛠️ Compilar Raylib Nativo (C++)
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: 📥 Clonar repositorio
        uses: actions/checkout@v4

      # 2. Instalar las herramientas de compilación de Windows en Linux
      - name: ⚙️ Configurar Cross-Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64

      # 3. Descomprimir el archivo ZIP local
      - name: 📦 Extraer dependencias locales de Raylib
        run: |
          echo "📦 Descomprimiendo Raylib desde el repositorio local..."
          unzip -q raylib-5.0_win64_mingw-w64.zip
          mv raylib-5.0_win64_mingw-w64 raylib_lib

      # 4. Compilar inyectando las librerías de forma estática dentro del .EXE
      - name: 🔨 Compilar Ejecutable Estático (.EXE)
        run: |
          mkdir builds
          # Se agregaron -static-libgcc y -static-libstdc++ para empaquetar las DLLs faltantes dentro del ejecutable
          x86_64-w64-mingw32-g++ juego.cpp -o builds/WarcraftMatch3.exe -Iraylib_lib/include -Lraylib_lib/lib -lraylib -lopengl32 -lgdi32 -lwinmm -static-libgcc -static-libstdc++ -mwindows

      # 5. Generar el Artefacto para descargar el juego listo
      - name: 📦 Guardar Juego Terminado
        uses: actions/upload-artifact@v4
        with:
          name: Warcraft_Match3_Raylib_Nativo
          path: builds/WarcraftMatch3.exe
          if-no-files-found: error
